"""create tables

Revision ID: de17b86d322f
Revises: 
Create Date: 2018-03-15 17:35:15.839797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de17b86d322f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gp_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_gp_id'), 'city', ['gp_id'], unique=True)
    op.create_index(op.f('ix_city_name'), 'city', ['name'], unique=True)
    op.create_table('flat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bnb_flat_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flat_bnb_flat_id'), 'flat', ['bnb_flat_id'], unique=True)
    op.create_index(op.f('ix_flat_name'), 'flat', ['name'], unique=True)
    op.create_table('calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_scraping', sa.Integer(), nullable=True),
    sa.Column('day_scraping', sa.String(length=60), nullable=True),
    sa.Column('night_price', sa.Integer(), nullable=True),
    sa.Column('scraping_location', sa.String(length=60), nullable=True),
    sa.Column('flat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flat_id'], ['flat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_time_scraping'), 'calendar', ['time_scraping'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_time_scraping'), table_name='calendar')
    op.drop_table('calendar')
    op.drop_index(op.f('ix_flat_name'), table_name='flat')
    op.drop_index(op.f('ix_flat_bnb_flat_id'), table_name='flat')
    op.drop_table('flat')
    op.drop_index(op.f('ix_city_name'), table_name='city')
    op.drop_index(op.f('ix_city_gp_id'), table_name='city')
    op.drop_table('city')
    # ### end Alembic commands ###
